apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: the-capy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hengkakada/backtest:v0.1
        ports:
        - containerPort: 8888
        
        # This is where the magic happens!
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
