apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: the-capy
type: Opaque
stringData:
  # This is exactly what you would normally put in your backend .env file
  DB_PASSWORD: "4hmS8Khen7Xdtai4VGanKEXEuWBxCLzj1ieOA6X8hqWk5IfMq0FsHexGPM4VLQIM"
